Adding post-processing master job dependency to cleanup the pipeline's working directory

diff --git a/resources/submit b/resources/submit
--- a/resources/submit
+++ b/resources/submit
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -euo
+set -eu
 
 function usage() { cat << EOF
 submit: Job submission wrapper script for the RNA-seek pipeline.
@@ -136,16 +136,22 @@ function submit(){
   # Run the workflow with specified executor
   case "$executor" in
     slurm)
+          # Create directory for logfiles
+          mkdir -p "$3"/logfiles/slurmfiles/
+          # Submit the master job to the cluster
           job_id=$(sbatch -J "$2" --gres=lscratch:100 --time=4-00:00:00 --mail-type=BEGIN,END,FAIL \
+          --output "$3"/logfiles/snakemake.log --error "$3"/logfiles/snakemake.err \
           snakemake --latency-wait 120 -s "$3"/workflow/Snakefile -d "$3" \
             --use-singularity --singularity-args "'-B $4'" --configfile="$3"/config.json \
             --printshellcmds --cluster-config "$3"/resources/cluster.json \
             --cluster "sbatch --gres {cluster.gres} --cpus-per-task {cluster.threads} -p {cluster.partition} -t {cluster.time} --mem {cluster.mem} --job-name={params.rname}" \
-            --keep-going --restart-times 3 -j 500 --rerun-incomplete --stats $3/resources/runtime_statistics.json \
-            2>&1 | tee -a $3/snakemake.log)
+            --keep-going --restart-times 3 -j 500 --rerun-incomplete --stats "$3"/logfiles/runtime_statistics.json \
+            2>&1 | tee -a "$3"/logfiles/master.log)
+          # Clean-up working directory after completion
+          cleanup_id=$(sbatch -J "clean_${2}" --dependency=afterany:${job_id} "$3"/cleanup "$3" "$job_id")
         ;;
       *)  echo "${executor} is not available." && \
-          fatal "Failed to provide valid cromwell backend: ${executor}. Please use either slurm."
+          fatal "Failed to provide valid execution backend: ${executor}. Please use slurm."
         ;;
     esac
 
